### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis.py#89]
When trying to use a bad producer name "<producer-name>",
the received error was `memphis: 'dict' object has no attribute 'replace'`

**Comment by idanasulinmemphis** [comment]
Thanks for the feedback, Fixed and will be released on the coming version
